#!/bin/bash
set -e

if ! id -u vpn-node > /dev/null 2>&1; then
    useradd --system --shell /bin/false vpn-node
fi

chown -R vpn-node:vpn-node /opt/nakolenke-vpn-node

systemctl daemon-reload
systemctl enable nakolenke-vpn-node.service

echo "VPN Node installed successfully."
